### PR TITLE
Feat/ad pods

### PR DESCRIPTION
**Pull request by delbeke**
This PR should better support ad-pods and ad-buffets so we can start implementing ad fallback when an ad fails to load.

### CODE REVIEW

**Comment by pietermees** [comment]
When I check files changed it says that nothing has changed?

**Comment by delbeke** [comment]
Strange, it has 3 commits with changes, how come no file has changed :s

**Comment by delbeke** [comment]
I must have done something wrong because the changes are already on the master branch.
I'll close this PR (since it is useless) and start a git course 😉

**Comment by pietermees** [comment]
Haha, ok :)

**Pull request closed without merging**
