### PR TITLE
Add prefetch hook

### PR DESCRIPTION
**Pull request by MerlierR**

### CODE REVIEW

**Review by timdp — COMMENTED** [review]
I'm not crazy about overriding functions/methods with getters and setters. Since we're starting from a class, why not recommend a subclass? That would be the orthodox OOP design if this were e.g. Java, right?

It does remind me of Node's streams, where you can either subclass e.g. `Readable` to implement `read()`, or use `new Readable({ read })` as a sort of shorthand. Perhaps that would be interesting here as well?

Regarding the name: `fetchUriReplacer` sounds like it's going to replace the fetch operation rather than parts of the URI. Suggestions: `formatUri`, `prepareUri`, `interpolateUri`.

One thing to watch out for is that each link in the chain will create a new loader. What would be a good way to share the replacement function between them? Traveling to the root from inner loaders?

**Comment by MerlierR** [comment]
@timdp right, we use a different VASTLoader for each fetch - that's why we override the VASTLoader prototype at the moment (in iab-vpaid).

I'll take a step back to think of a different fix.

**Comment by MerlierR** [comment]
@timdp I've put the URI preparation step in the `options` object with a default to a passthrough. That should handle all previous concerns I think

**Review by timdp — APPROVED** [review]

**Comment by timdp** [comment]
Published as v2.4.0.

**Pull request merged**
